version: '3.8'

services:
  relmgmtpostgres:
    image: postgres:16
    container_name: relmgmtpostgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bBzp16eHfA29wZUvr
      POSTGRES_DB: relmgmt
    ports:
      - '5432:5432'
    networks:
      - relmgmtnet
    volumes:
      - relmgmt_postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: john.doe@polycoder.com
      PGADMIN_DEFAULT_PASSWORD: devpgadmin
    ports:
      - '5050:80'
    networks:
      - relmgmtnet
    depends_on:
      - relmgmtpostgres

networks:
  relmgmtnet:
    driver: bridge

volumes:
  relmgmt_postgres_data: 