-- Add new phases to the check constraint
ALTER TABLE phases DROP CONSTRAINT chk_phase_type;
ALTER TABLE phases ADD CONSTRAINT chk_phase_type CHECK (phase_type IN ('FUNCTIONAL_DESIGN', 'TECHNICAL_DESIGN', 'BUILD', 'SYSTEM_INTEGRATION_TEST', 'USER_ACCEPTANCE_TEST', 'REGRESSION_TESTING', 'DATA_COMPARISON', 'SMOKE_TESTING', 'PRODUCTION_GO_LIVE'));
