name: Backend CI/CD

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'relmgmt/backend/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'relmgmt/backend/**'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_PASSWORD: test
          POSTGRES_DB: testdb
          POSTGRES_USER: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x relmgmt/backend/gradlew

    - name: Run tests
      run: |
        cd relmgmt/backend
        ./gradlew test

    - name: Build application
      run: |
        cd relmgmt/backend
        ./gradlew build -x test

    - name: Run integration tests
      run: |
        cd relmgmt/backend
        ./gradlew integrationTest

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: relmgmt/backend/build/reports/tests/
        retention-days: 30

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: relmgmt/backend/build/libs/
        retention-days: 30 